# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.0_1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.0_1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/connorosburn/some_promises/mnist_classifier

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/connorosburn/some_promises/mnist_classifier

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.0_1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.0_1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/connorosburn/some_promises/mnist_classifier/CMakeFiles /Users/connorosburn/some_promises/mnist_classifier/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/connorosburn/some_promises/mnist_classifier/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mnist

# Build rule for target.
mnist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mnist
.PHONY : mnist

# fast build rule for target.
mnist/fast:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/build
.PHONY : mnist/fast

lib/MNISTFashion/MNISTLoader.o: lib/MNISTFashion/MNISTLoader.cpp.o

.PHONY : lib/MNISTFashion/MNISTLoader.o

# target to build an object file
lib/MNISTFashion/MNISTLoader.cpp.o:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/MNISTFashion/MNISTLoader.cpp.o
.PHONY : lib/MNISTFashion/MNISTLoader.cpp.o

lib/MNISTFashion/MNISTLoader.i: lib/MNISTFashion/MNISTLoader.cpp.i

.PHONY : lib/MNISTFashion/MNISTLoader.i

# target to preprocess a source file
lib/MNISTFashion/MNISTLoader.cpp.i:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/MNISTFashion/MNISTLoader.cpp.i
.PHONY : lib/MNISTFashion/MNISTLoader.cpp.i

lib/MNISTFashion/MNISTLoader.s: lib/MNISTFashion/MNISTLoader.cpp.s

.PHONY : lib/MNISTFashion/MNISTLoader.s

# target to generate assembly for a file
lib/MNISTFashion/MNISTLoader.cpp.s:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/MNISTFashion/MNISTLoader.cpp.s
.PHONY : lib/MNISTFashion/MNISTLoader.cpp.s

lib/NeuralNetwork/Layer/ConvolutionalLayer.o: lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.o

.PHONY : lib/NeuralNetwork/Layer/ConvolutionalLayer.o

# target to build an object file
lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.o:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.o
.PHONY : lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.o

lib/NeuralNetwork/Layer/ConvolutionalLayer.i: lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.i

.PHONY : lib/NeuralNetwork/Layer/ConvolutionalLayer.i

# target to preprocess a source file
lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.i:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.i
.PHONY : lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.i

lib/NeuralNetwork/Layer/ConvolutionalLayer.s: lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.s

.PHONY : lib/NeuralNetwork/Layer/ConvolutionalLayer.s

# target to generate assembly for a file
lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.s:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.s
.PHONY : lib/NeuralNetwork/Layer/ConvolutionalLayer.cpp.s

lib/NeuralNetwork/Layer/Layer.o: lib/NeuralNetwork/Layer/Layer.cpp.o

.PHONY : lib/NeuralNetwork/Layer/Layer.o

# target to build an object file
lib/NeuralNetwork/Layer/Layer.cpp.o:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/Layer.cpp.o
.PHONY : lib/NeuralNetwork/Layer/Layer.cpp.o

lib/NeuralNetwork/Layer/Layer.i: lib/NeuralNetwork/Layer/Layer.cpp.i

.PHONY : lib/NeuralNetwork/Layer/Layer.i

# target to preprocess a source file
lib/NeuralNetwork/Layer/Layer.cpp.i:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/Layer.cpp.i
.PHONY : lib/NeuralNetwork/Layer/Layer.cpp.i

lib/NeuralNetwork/Layer/Layer.s: lib/NeuralNetwork/Layer/Layer.cpp.s

.PHONY : lib/NeuralNetwork/Layer/Layer.s

# target to generate assembly for a file
lib/NeuralNetwork/Layer/Layer.cpp.s:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/Layer.cpp.s
.PHONY : lib/NeuralNetwork/Layer/Layer.cpp.s

lib/NeuralNetwork/Layer/MaxPoolingLayer.o: lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.o

.PHONY : lib/NeuralNetwork/Layer/MaxPoolingLayer.o

# target to build an object file
lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.o:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.o
.PHONY : lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.o

lib/NeuralNetwork/Layer/MaxPoolingLayer.i: lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.i

.PHONY : lib/NeuralNetwork/Layer/MaxPoolingLayer.i

# target to preprocess a source file
lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.i:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.i
.PHONY : lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.i

lib/NeuralNetwork/Layer/MaxPoolingLayer.s: lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.s

.PHONY : lib/NeuralNetwork/Layer/MaxPoolingLayer.s

# target to generate assembly for a file
lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.s:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.s
.PHONY : lib/NeuralNetwork/Layer/MaxPoolingLayer.cpp.s

lib/NeuralNetwork/Layer/SoftmaxLayer.o: lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.o

.PHONY : lib/NeuralNetwork/Layer/SoftmaxLayer.o

# target to build an object file
lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.o:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.o
.PHONY : lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.o

lib/NeuralNetwork/Layer/SoftmaxLayer.i: lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.i

.PHONY : lib/NeuralNetwork/Layer/SoftmaxLayer.i

# target to preprocess a source file
lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.i:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.i
.PHONY : lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.i

lib/NeuralNetwork/Layer/SoftmaxLayer.s: lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.s

.PHONY : lib/NeuralNetwork/Layer/SoftmaxLayer.s

# target to generate assembly for a file
lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.s:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.s
.PHONY : lib/NeuralNetwork/Layer/SoftmaxLayer.cpp.s

lib/NeuralNetwork/Neuron.o: lib/NeuralNetwork/Neuron.cpp.o

.PHONY : lib/NeuralNetwork/Neuron.o

# target to build an object file
lib/NeuralNetwork/Neuron.cpp.o:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Neuron.cpp.o
.PHONY : lib/NeuralNetwork/Neuron.cpp.o

lib/NeuralNetwork/Neuron.i: lib/NeuralNetwork/Neuron.cpp.i

.PHONY : lib/NeuralNetwork/Neuron.i

# target to preprocess a source file
lib/NeuralNetwork/Neuron.cpp.i:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Neuron.cpp.i
.PHONY : lib/NeuralNetwork/Neuron.cpp.i

lib/NeuralNetwork/Neuron.s: lib/NeuralNetwork/Neuron.cpp.s

.PHONY : lib/NeuralNetwork/Neuron.s

# target to generate assembly for a file
lib/NeuralNetwork/Neuron.cpp.s:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Neuron.cpp.s
.PHONY : lib/NeuralNetwork/Neuron.cpp.s

lib/NeuralNetwork/Weight.o: lib/NeuralNetwork/Weight.cpp.o

.PHONY : lib/NeuralNetwork/Weight.o

# target to build an object file
lib/NeuralNetwork/Weight.cpp.o:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Weight.cpp.o
.PHONY : lib/NeuralNetwork/Weight.cpp.o

lib/NeuralNetwork/Weight.i: lib/NeuralNetwork/Weight.cpp.i

.PHONY : lib/NeuralNetwork/Weight.i

# target to preprocess a source file
lib/NeuralNetwork/Weight.cpp.i:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Weight.cpp.i
.PHONY : lib/NeuralNetwork/Weight.cpp.i

lib/NeuralNetwork/Weight.s: lib/NeuralNetwork/Weight.cpp.s

.PHONY : lib/NeuralNetwork/Weight.s

# target to generate assembly for a file
lib/NeuralNetwork/Weight.cpp.s:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/NeuralNetwork/Weight.cpp.s
.PHONY : lib/NeuralNetwork/Weight.cpp.s

lib/main.o: lib/main.cpp.o

.PHONY : lib/main.o

# target to build an object file
lib/main.cpp.o:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/main.cpp.o
.PHONY : lib/main.cpp.o

lib/main.i: lib/main.cpp.i

.PHONY : lib/main.i

# target to preprocess a source file
lib/main.cpp.i:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/main.cpp.i
.PHONY : lib/main.cpp.i

lib/main.s: lib/main.cpp.s

.PHONY : lib/main.s

# target to generate assembly for a file
lib/main.cpp.s:
	$(MAKE) -f CMakeFiles/mnist.dir/build.make CMakeFiles/mnist.dir/lib/main.cpp.s
.PHONY : lib/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mnist"
	@echo "... lib/MNISTFashion/MNISTLoader.o"
	@echo "... lib/MNISTFashion/MNISTLoader.i"
	@echo "... lib/MNISTFashion/MNISTLoader.s"
	@echo "... lib/NeuralNetwork/Layer/ConvolutionalLayer.o"
	@echo "... lib/NeuralNetwork/Layer/ConvolutionalLayer.i"
	@echo "... lib/NeuralNetwork/Layer/ConvolutionalLayer.s"
	@echo "... lib/NeuralNetwork/Layer/Layer.o"
	@echo "... lib/NeuralNetwork/Layer/Layer.i"
	@echo "... lib/NeuralNetwork/Layer/Layer.s"
	@echo "... lib/NeuralNetwork/Layer/MaxPoolingLayer.o"
	@echo "... lib/NeuralNetwork/Layer/MaxPoolingLayer.i"
	@echo "... lib/NeuralNetwork/Layer/MaxPoolingLayer.s"
	@echo "... lib/NeuralNetwork/Layer/SoftmaxLayer.o"
	@echo "... lib/NeuralNetwork/Layer/SoftmaxLayer.i"
	@echo "... lib/NeuralNetwork/Layer/SoftmaxLayer.s"
	@echo "... lib/NeuralNetwork/Neuron.o"
	@echo "... lib/NeuralNetwork/Neuron.i"
	@echo "... lib/NeuralNetwork/Neuron.s"
	@echo "... lib/NeuralNetwork/Weight.o"
	@echo "... lib/NeuralNetwork/Weight.i"
	@echo "... lib/NeuralNetwork/Weight.s"
	@echo "... lib/main.o"
	@echo "... lib/main.i"
	@echo "... lib/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

